FROM elixir:1.15-alpine

ARG PORT MIX_ENV
ENV PORT=${PORT:-4000}
ENV MIX_ENV=${MIX_ENV:-dev}

RUN apk --no-cache upgrade
RUN apk --no-cache add inotify-tools

WORKDIR /opt/app

# Phoenix
RUN mix local.hex --force
RUN mix local.rebar --force
ADD mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV

RUN mkdir config
ADD config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile --only $MIX_ENV
RUN mix phx.gen.cert --output /etc/ssl/selfsigned

EXPOSE $PORT
CMD [ "mix", "phx.server" ]
