version: "3"

services:
  postgres:
    container_name: odpyt-postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: lolek
      POSTGRES_PASSWORD: tajne
      POSTGRES_DB: odpyt
      PGDATA: /var/lib/postgresql/data

  odpyt:
    container_name: odpyt
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./assets:/opt/app/assets
      - ./config:/opt/app/config
    environment:
      POSTGRES_USER: lolek
      POSTGRES_PASSWORD: tajne
      POSTGRES_DB: odpyt
      POSTGRES_HOST: odpyt-postgres
      POSTGRES_PORT: 5432
      SECRET_KEY: rmtpozvzdmhmyjsnnpjbzhsvyruvqscdgvvwuihwyoiaseksjabwzizzjwebnbog
      KEYFILE_PATH: /etc/ssl/selfsigned_key.pem
      CERTFILE_PATH: /etc/ssl/selfsigned.pem
